Feature/review 1
Devinear/Transportation pull request #3
Opened 2020-01-23 01:16 UTC by Devinear

branch Feature/review_1 > branch develop

2020-01-25 03:19 UTC, dev-newbie-randy approved these changes

2020-01-27 11:06 UTC, 2giwon requested changes

2020-01-27 11:06 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/data/unit/BusStopData.kt
>      fun clone() = database.clone() as ArrayList<BusStopData>
clone을 해주는 이유가 있나요?

2020-01-27 11:06 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/data/unit/BookmarkData.kt
> +    }
함수의 작업은 add인데 넘겨주는 값이 마지막 인덱스 값 입니다. 

불필요한 동작이 추가 되어 있어서 다른 사람이 함수를 사용할 때 혼동이 있을 것 같습니다.

다른 함수로 분리를 하던지 제거를 해주는 것도 좋아 보입니다.

2020-01-27 11:06 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +    var items = ArrayList<Any>()
var로 사용한 이유가 있나요?

2020-01-27 11:06 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        (0 until BookmarkDatabase.count()).forEach { i -> items.add(BookmarkDatabase.get(i)) }
이렇게 하는 것 보다는 함수 파라메터로 BookmarkDatabase아이템들을 받고 addAll로 처리를 하는 것이 나아 보입니다.

하지만 지금 구조상 변경이 힘들다면 참고만 해두는 것도 좋겠습니다.

수정하지 않으셔도 됩니다.

2020-01-27 11:06 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        holder.tvSub.text   = sub
var로 받지 않고 val로 할 수 있을 것 같습니다. when으로 처리하고 두 개의 변수를 동시에 받으면 될 것 같습니다.

2020-01-27 11:06 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        (0 until BookmarkDatabase.count()).forEach { i -> items.add(BookmarkDatabase.get(i)) }
그리고 이렇게 하면 중복된 즐겨찾기가 있을 것 같습니다. 중복 추가를 못하게 처리해주세요

2020-01-28 14:26 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        holder.tvSub.text   = sub
지역변수를 없애는 방향으로 수정하였습니다.

2020-01-28 14:52 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        (0 until BookmarkDatabase.count()).forEach { i -> items.add(BookmarkDatabase.get(i)) }
clear 후 getAll 및 addAll 동작을 변경하였습니다.

2020-01-28 14:52 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +    var items = ArrayList<Any>()
private val 로 변경하였습니다.

2020-01-28 14:53 UTC, Devinear commented on app/src/main/java/com/custom/transportation/data/unit/BookmarkData.kt
> +    }
last index 를 전달하는 동작을 제거하였습니다.

2020-01-28 14:53 UTC, Devinear commented on app/src/main/java/com/custom/transportation/data/unit/BusStopData.kt
>      fun clone() = database.clone() as ArrayList<BusStopData>
database의 모든 데이터를 getAll 동작으로 가져가도록 수정하였습니다.

2020-01-29 00:57 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/data/unit/BusStopData.kt
>      fun clone() = database.clone() as ArrayList<BusStopData>
@Devinear 커밋 아이디 넣어주세요

2020-01-29 00:57 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/data/unit/BusStopData.kt
>      fun clone() = database.clone() as ArrayList<BusStopData>
리졸브 처리하지 마세요

2020-01-29 00:57 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/data/unit/BookmarkData.kt
> +    }
@Devinear 커밋 아이디 넣어주세요

2020-01-29 00:58 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +    var items = ArrayList<Any>()
@Devinear 커밋 아이디 넣어주세요

2020-01-29 00:58 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        (0 until BookmarkDatabase.count()).forEach { i -> items.add(BookmarkDatabase.get(i)) }
@Devinear 커밋 아이디 넣어주세요

2020-01-29 00:58 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        holder.tvSub.text   = sub
@Devinear 커밋 아이디 넣어주세요

2020-01-29 00:59 UTC, 2giwon requested changes
@Devinear 커밋 아이디 넣어주세요

2020-01-29 01:12 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        holder.tvSub.text   = sub
fedad1a576687ac8d07a83808b7230126ea4d546

2020-01-29 01:12 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +        (0 until BookmarkDatabase.count()).forEach { i -> items.add(BookmarkDatabase.get(i)) }
818104e329ca3afe980d25ab5c8042b2b770b25a

2020-01-29 01:12 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +    var items = ArrayList<Any>()
818104e329ca3afe980d25ab5c8042b2b770b25a

2020-01-29 01:12 UTC, Devinear commented on app/src/main/java/com/custom/transportation/data/unit/BookmarkData.kt
> +    }
818104e329ca3afe980d25ab5c8042b2b770b25a

2020-01-29 01:12 UTC, Devinear commented on app/src/main/java/com/custom/transportation/data/unit/BusStopData.kt
>      fun clone() = database.clone() as ArrayList<BusStopData>
818104e329ca3afe980d25ab5c8042b2b770b25a

2020-01-30 07:24 UTC, 2giwon approved these changes
수고하셨습니다

2020-01-30 07:28 UTC, merged