Feature/retrofit
Devinear/Transportation pull request #5
Opened 2020-01-30 07:38 UTC by Devinear

Retrofit에 대한 리뷰 요청 드립니다.

2020-01-30 08:00 UTC, dev-newbie-randy commented
.idea/ 하위 폴더는 업로드 안 하는 게 나을 거 같습니다.

2020-01-30 08:06 UTC, dev-newbie-randy approved these changes

2020-02-03 03:56 UTC, 2giwon requested changes

2020-02-03 03:56 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/data/retrofit/RetrofitHelper.kt
> +                level = HttpLoggingInterceptor.Level.BODY
디버그 상태와 릴리즈 상태일때 다른 level을 넣어주는 걸 추천드립니다

2020-02-03 03:56 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/data/unit/BusInfoData.kt
> +        fun makeData(name: String, time: String, direction: String, before: String, after: String)
싱글턴을 사용하신다면 getInstance로 하는게 좋습니다.

2020-02-03 06:44 UTC, Devinear commented on app/src/main/java/com/custom/transportation/data/unit/BusInfoData.kt
> +        fun makeData(name: String, time: String, direction: String, before: String, after: String)
BusInfoData 라는 객체의 생성을 의미하며, 동시에 생성하지 못하도록 하고 싶어 위와 같이 작성하였습니다.
여러 객체가 필요하므로 싱글턴 패턴은 사용할 수 없을 것 같습니다.

2020-02-03 07:09 UTC, Devinear commented on app/src/main/java/com/custom/transportation/data/retrofit/RetrofitHelper.kt
> +                level = HttpLoggingInterceptor.Level.BODY
디버그 모드일 경우에만 로그를 출력하도록 수정하였습니다.
cd9679b

2020-02-03 07:15 UTC, 2giwon approved these changes

2020-02-03 07:19 UTC, merged