Feature/mvp
Devinear/Transportation pull request #6
Opened 2020-02-03 16:59 UTC by Devinear

리뷰를 요청 드립니다.

2020-02-04 01:23 UTC, dev-newbie-randy approved these changes

2020-02-04 05:13 UTC, 2giwon requested changes

2020-02-04 05:13 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/MainActivity.kt
> +                    fab.setOnClickListener(pagerAdapter.getItem(curTabType.pos).fabClickListener)
onTabSelected에서 온클릭 리스너를 등록하는 건지 궁금합니다. 이럴 경우 탭이 선택될때 마다 리스너를 등록할거 같아 보입니다.

2020-02-04 05:13 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/model/BusStopModel.kt
> +            }
BusStopDatabase의 역할이 무엇인지 궁금합니다. List를 커스텀하게 쓰기위한 것인가요?

그렇다면 그냥 멤버 변수로 Mutablelist를 갖고 있는 편이 나아 보입니다.

그렇게 하면 for문을 쓰지 않고 addAll로 처리가 가능합니다.

2020-02-04 05:13 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +    fun addItems(items : ArrayList<BusStopData>) {
ArrayList로 받을 필요는 없어보입니다.

2020-02-04 05:13 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
>  class BusStopAdapter(val fragment: BusStopFragment) : RecyclerView.Adapter<BusStopAdapter.ViewHolder>() {
adapter에 fragment는 순환 참조이기 때문에 좋아보이지 않습니다.

2020-02-04 10:38 UTC, Devinear commented on app/src/main/java/com/custom/transportation/MainActivity.kt
> +                    fab.setOnClickListener(pagerAdapter.getItem(curTabType.pos).fabClickListener)
해당 동작의 경우 각 페이지의 마다 서로 다른 동작을 지원하기 위함 입니다.
fab의 경우 모든 페이지가 공통으로 사용되기 때문에 그 페이지에서 원하는 동작을 등록합니다.

2020-02-04 14:21 UTC, Devinear commented on app/src/main/java/com/custom/transportation/model/BusStopModel.kt
> +            }
Room을 사용하기전에 App에서 사용하는 임시 저장소의 느낌으로 사용하고자 하였습니다.
다음 목표인 Room을 사용하는 과정에서 해당 부분은 변경될 계획입니다.

2020-02-04 14:30 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +    fun addItems(items : ArrayList<BusStopData>) {
mutableListOf, List 구조로 변경하였습니다.
cb47989

2020-02-04 14:47 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
>  class BusStopAdapter(val fragment: BusStopFragment) : RecyclerView.Adapter<BusStopAdapter.ViewHolder>() {
해당 구조를 변경하였습니다.
bookmark 추가를 위한 presenter를 참조하도록 하였습니다.
e27f6a8

2020-02-05 01:44 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +    fun addItems(items : ArrayList<BusStopData>) {
잘못된 커밋 리비전을 남긴것 같습니다. 확인 부탁드립니다.

2020-02-05 01:45 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
>  class BusStopAdapter(val fragment: BusStopFragment) : RecyclerView.Adapter<BusStopAdapter.ViewHolder>() {
@Devinear 여기도 잘못된 리비전 번호입니다

2020-02-05 01:45 UTC, 2giwon requested changes
수정된 리비전 번호가 잘못된 것 같습니다. 확인 부탁드립니다.

2020-02-05 01:56 UTC, Devinear commented on app/src/main/java/com/custom/transportation/MainActivity.kt
> +                    fab.setOnClickListener(pagerAdapter.getItem(curTabType.pos).fabClickListener)
해당 동작은 다음 브랜치에서 구조 개선 예정입니다

2020-02-05 01:56 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +    fun addItems(items : ArrayList<BusStopData>) {
위의 코멘트에 수정하였습니다.

2020-02-05 01:56 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
>  class BusStopAdapter(val fragment: BusStopFragment) : RecyclerView.Adapter<BusStopAdapter.ViewHolder>() {
위의 코멘트에 수정하였습니다.

2020-02-05 01:56 UTC, Devinear commented
> 수정된 리비전 번호가 잘못된 것 같습니다. 확인 부탁드립니다.

2020-02-05 01:59 UTC, 2giwon approved these changes
수고하셨습니다 👍

2020-02-05 02:13 UTC, merged