2차 리뷰 결과(디자인 변경) 및 즐겨찾기 DB 구축
Devinear/Transportation pull request #7
Opened 2020-02-10 08:31 UTC by Devinear

리뷰를 요청 드립니다. ^^

2020-02-10 08:44 UTC, dev-newbie-randy commented on app/build.gradle
> +
com.android.support:cardview를 androidx의 것으로 대체하는 게 좋습니다.

2020-02-10 09:02 UTC, dev-newbie-randy commented on app/src/main/java/com/custom/transportation/repository/model/BusInfoModel.kt
> +            route.compareTo("8") == 0 -> RouteType.GTEONGGI
compareTo 구문없이 짜는 게 좀 더 깔끔할 것 같습니다.

2020-02-10 09:04 UTC, dev-newbie-randy commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +                Snackbar.make(it, it.context.getText(R.string.add_bookmark), Snackbar.LENGTH_SHORT).show()
return@setOnLongClickListener true 부분은 없어도 되지 않을까요?

2020-02-10 14:58 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +                Snackbar.make(it, it.context.getText(R.string.add_bookmark), Snackbar.LENGTH_SHORT).show()
일반 ClickListener과 다르게 LongClickListener의 경우 해당 동작을 끝낼지 여부에 대해 return 값을 전달해주어야 합니다.
혹 return을 하지 않고 다른 방법이 있을까요?

2020-02-10 15:04 UTC, Devinear commented on app/build.gradle
> +
아직은 사용하지 않는 dependency 이므로 제거 하겠습니다.
다음 번 머테리얼 디자인을 적용하며 위의 것으로 대체하여 사용하겠습니다.

89e4ca9

2020-02-10 15:05 UTC, Devinear commented on app/src/main/java/com/custom/transportation/repository/model/BusInfoModel.kt
> +            route.compareTo("8") == 0 -> RouteType.GTEONGGI
조건을 간소화하였습니다.

4b02da7

2020-02-11 00:25 UTC, dev-newbie-randy commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +                Snackbar.make(it, it.context.getText(R.string.add_bookmark), Snackbar.LENGTH_SHORT).show()
아;;; 제가 리뷰 잘 못 했습니다 ㅠㅠ
죄송합니다 ㅠㅠ

2020-02-11 00:25 UTC, dev-newbie-randy approved these changes

2020-02-11 15:29 UTC, 2giwon requested changes

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/fragment/BusNumberFragment.kt
> +                setPositiveButton(context!!.getString(android.R.string.ok)) { dialog: DialogInterface?, which:Int -> }
!!는 지양하는 것이 좋을 것 같습니다.

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/fragment/BusNumberFragment.kt
> +                    filters = Array(1) {
filter에 array로 넘겨줘야 해서 이렇게 하셨나요?  맞다면 arrayOf 같은 걸 써보는 것은 어떨까요?

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +                Snackbar.make(it, it.context.getText(R.string.add_bookmark), Snackbar.LENGTH_SHORT).show()
만약 add가 실패하면 어떻게 되나요?

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/repository/model/BookmarkModel.kt
> +    fun deleteBookmark(bookmark: Any) : Boolean = bookmarks.remove(bookmark)
Any 로 처리하신 이유가 있나요?

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/res/layout/item_bookmark.xml
> +        android:layout_margin="15dp"
보통 마진값은 4 배수로 처리하는게 좋습니다.

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/repository/local/BookmarkDB.kt
> +                .fallbackToDestructiveMigration()
이것은 넣으신 이유가 있나요? 어떤 역할을 하는 지 궁금합니다.

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/repository/local/Converts.kt
> +class Converts {
이 convert는 어떤 용도를 쓰이는 건가요?

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/repository/model/BookmarkModel.kt
> +                it.presenter = newPresenter
모델이 presenter를 갖는 것은 좋지 않은 방법입니다. 모델은 어떠한 것의 소유도 되어서는 안됩니다.

또한 모델 보다 데이터 소스, 리파지토리 형태로 만드는게 어떨까요?

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/contract/BusStopPresenter.kt
> +    override fun addBookmark(bookmark: Any) = BookmarkModel.getInstance(this).addBookmark(bookmark)
모델 인스턴스를 가져오는 것보다 인터페이스로 전달하는 것이 좋아 보입니다.

2020-02-11 15:29 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/view/fragment/BusStopFragment.kt
> +    private lateinit var tvEmpty : TextView
지연초기화를 하는 이유가 있나요?

2020-02-12 01:32 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/fragment/BusNumberFragment.kt
> +                setPositiveButton(context!!.getString(android.R.string.ok)) { dialog: DialogInterface?, which:Int -> }
불필요한 '!!'을 제거 하였습니다.

2020-02-12 01:41 UTC, Devinear commented on app/src/main/java/com/custom/transportation/repository/model/BookmarkModel.kt
> +    fun deleteBookmark(bookmark: Any) : Boolean = bookmarks.remove(bookmark)
bookmark의 경우 정류장 객체와 버스 객체로 나뉘게 됩니다.
각각의 list를 따로 들고 있는것보다 두 객체의 타입에 관계없이 하나의 list로 관리하는 것이 좋겠다고 생각되어 any 타입으로 add 및 delete를 진행합니다.

2020-02-12 01:47 UTC, Devinear commented on app/src/main/java/com/custom/transportation/repository/local/BookmarkDB.kt
> +                .fallbackToDestructiveMigration()
fallbackToDestructiveMigration 옵션의 경우 별도의 마이그레이션을 하지 않아도 자동으로 기존의 테이블을 삭제하고 새로운 내용으로 테이블을 생성하는 옵션입니다.

2020-02-12 01:49 UTC, Devinear commented on app/src/main/java/com/custom/transportation/repository/local/Converts.kt
> +class Converts {
원래의 Database에는 int, string 등의 기본적인 타입만 지원합니다. 
해당 지원하지않는 커스텀한 객체를 database에 넣길 원하는 경우 해당 객체를 지원하는 타입으로 변환하는 동작이 필요합니다.
해당 클래스는 BusInfoData, BusStopData를 String 타입으로 서로 변환하는 동작을 지원합니다.

2020-02-12 01:53 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/view/fragment/BusStopFragment.kt
> +    private lateinit var tvEmpty : TextView
BusStopFragment의 경우 해당 TextView를 사용하는 시점이 onCreateView 이후라고 판단이 되어 nullable을 허용하지 않기 위해 지연초기화를 하였습니다.

2020-02-12 01:56 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/fragment/BusNumberFragment.kt
> +                    filters = Array(1) {
filter에는 항상 array를 설정하여야하기 때문입니다.
아직 모르는 세계가 많습니다. 권해주신 arrayOf를 사용해보았습니다. -_-b
ef4ad75

2020-02-12 01:57 UTC, Devinear commented on app/src/main/res/layout/item_bookmark.xml
> +        android:layout_margin="15dp"
마진값을 변경 및 dimen 등록하였습니다.
6bd1bef

2020-02-14 01:25 UTC, Devinear commented on app/src/main/java/com/custom/transportation/repository/model/BookmarkModel.kt
> +                it.presenter = newPresenter
Model의 좀더 명확한 이름으로 변경 및 Callback 구조를 추가했습니다.
전체적으로 가다듬는 추가적인 작업이 필요할 듯 싶습니다.

ab3bb07

2020-02-14 01:26 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/contract/BusStopPresenter.kt
> +    override fun addBookmark(bookmark: Any) = BookmarkModel.getInstance(this).addBookmark(bookmark)
위의 코멘트와 같이 Callback 구조를 추가하였습니다.

ab3bb07

2020-02-14 07:01 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BusStopAdapter.kt
> +                Snackbar.make(it, it.context.getText(R.string.add_bookmark), Snackbar.LENGTH_SHORT).show()
@Devinear 이거는 수정안해주셨느데 ㅠㅠ

2020-02-14 07:03 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/repository/model/BookmarkModel.kt
> +    fun deleteBookmark(bookmark: Any) : Boolean = bookmarks.remove(bookmark)
음 그럼 이거는 common 하게 사용되는 거니 base 에 만드시는 걸 추천드립니다.

제네릭을 써보는게 어떨까 하는데 어려우시면 그냥 진행하셔도 됩니다.

2020-02-14 07:04 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/repository/local/BookmarkDB.kt
> +                .fallbackToDestructiveMigration()
이런 것도 있었군요 room을 더 공부해야할 것 같습니다. 덕분에 하나 알아갑니다

2020-02-14 07:48 UTC, 2giwon requested changes
1개 수정 안하신거 있는데 그냥 진행하시는 건가요?

2020-02-14 09:33 UTC, 2giwon approved these changes

2020-02-14 15:53 UTC, merged