전체적인 코드 개선 및 즐겨찾기 Swipe, Tag 추가 동작 추가
Devinear/Transportation pull request #8
Opened 2020-02-26 09:10 UTC by Devinear

2020-02-26 09:32 UTC, 2giwon requested changes

2020-02-26 09:32 UTC, 2giwon commented on app/src/main/res/layout/layout_tag.xml
> +            android:hint="추가하고 싶은 태그가 있나요?" />
힌트는 보여지는 UI이기 때문에 String 리소스로 관리되는게 좋습니다.

2020-02-26 09:32 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +                }.create().run { show() }
런을 안해도 되요 빌더 패턴이라서 바로 show 해도 됩니다.

2020-02-26 12:52 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +                }.create().run { show() }
오오 제거하였습니다.

85e4ce1

2020-02-26 12:53 UTC, Devinear commented on app/src/main/res/layout/layout_tag.xml
> +            android:hint="추가하고 싶은 태그가 있나요?" />
리소스 정리를 하였습니다.

85e4ce1

2020-02-26 12:57 UTC, dev-newbie-randy submitted a review, later dismissed
스터디 시간 외에 추가 커밋된 내용들 위주로 리뷰하였습니다~

2020-02-27 04:27 UTC, 2giwon commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +                }.create().run { show() }
show()가 빠졌어요

2020-02-27 05:22 UTC, Devinear commented on app/src/main/java/com/custom/transportation/ui/adapter/recycler/BookmarkAdapter.kt
> +                }.create().run { show() }
show()가 없어도 활성화되는 줄 알았는데.. 
그래서 오오를 외쳤는데..
테스트 해보고 실제로 되길래 육성으로 오오 했는데..
그 아래의 태그 추가 다이얼로그를 활성화 한 것 이군요..

2a68501

2020-02-28 00:12 UTC, 2giwon approved these changes
수고하셨습니다

2020-02-28 05:40 UTC, dev-newbie-randy approved these changes

2020-02-28 10:32 UTC, merged